name: wofroho_mobile
description: A new Flutter project.

publish_to: "none"

version: 1.1.1+5

environment:
  sdk: ">=3.3.0 <4.0.0"

dependencies:
  animations: ^2.0.11
  cloud_firestore: ^4.15.5
  firebase_app_check: ^0.2.1+14
  firebase_auth: ^4.17.5
  firebase_core: ^2.25.4
  firebase_storage: ^11.6.6
  flutter:
    sdk: flutter
  flutter_svg: ^2.0.10+1
  image_picker: ^1.0.7
  intl: ^0.19.0
  shared_preferences: ^2.2.2

dev_dependencies:
  flutter_launcher_icons: ^0.13.1
  flutter_native_splash: ^2.2.18
  flutter_test:
    sdk: flutter

# Run with: flutter pub run flutter_launcher_icons:main
flutter_icons:
  android: true
  ios: true
  image_path: "assets/launcher_icons/wofroho_icon_full.png"
  adaptive_icon_foreground: "assets/launcher_icons/wofroho_icon.png"
  adaptive_icon_background: "#3756F6"

# Run with: flutter pub pub run flutter_native_splash:create
flutter_native_splash:
  android: true
  ios: true
  image: "assets/launcher_icons/wofroho_splash_icon.png"
  color: "#3756F6"
  android_disable_fullscreen: true

flutter:
  uses-material-design: true

  assets:
    - assets/images/wofroho.svg
    - assets/images/wofroho_logo_full.svg
    - assets/images/settings.svg
    - assets/images/microsoft_logo.svg
    - assets/images/confetti.svg
    - assets/images/party_popper.svg
    - assets/images/close.svg
    - assets/images/back.svg
    - assets/images/check.svg
    - assets/images/error.svg
    - assets/images/add.svg
    - assets/images/minimise.svg
    - assets/images/camera.svg
    - assets/images/libary.svg
    - assets/images/menu.svg
    - assets/images/arrow_right.svg
    - assets/images/arrow_left.svg

  fonts:
    - family: Poppins
      fonts:
        - asset: assets/fonts/Poppins-Regular.ttf
        - asset: assets/fonts/Poppins-Italic.ttf
          style: italic
        - asset: assets/fonts/Poppins-Bold.ttf
          weight: 700
        - asset: assets/fonts/Poppins-BoldItalic.ttf
          style: italic
          weight: 700
