name: wofroho_mobile
description: A new Flutter project.

publish_to: "none"

version: 1.0.0+1

environment:
  sdk: ">=2.7.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter

  flutter_svg: ^0.19.1
  intl: ^0.16.1
  image_picker: ^0.6.7+17
  animations: ^1.1.2

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_launcher_icons: "^0.8.0"
  flutter_native_splash: ^0.1.9

# Run with: flutter pub run flutter_launcher_icons:main
flutter_icons:
  android: true
  ios: false # iOS done manually at this stage
  image_path: "assets/wofroho_logo.png"

# Run with: flutter pub pub run flutter_native_splash:create
flutter_native_splash:
  ios: false # iOS done manually at this stage
  image: "assets/wofroho_logo_full.png"
  color: "3756F6"
  android_disable_fullscreen: true

flutter:
  uses-material-design: true

  assets:
    - assets/images/wofroho.svg
    - assets/images/wofroho_logo_full.svg
    - assets/images/settings.svg
    - assets/images/microsoft_logo.svg
    - assets/images/confetti.svg
    - assets/images/party_popper.svg
    - assets/images/close.svg
    - assets/images/back.svg
    - assets/images/check.svg
    - assets/images/error.svg
    - assets/images/add.svg
    - assets/images/minimise.svg
    - assets/images/camera.svg
    - assets/images/libary.svg

  fonts:
    - family: Poppins
      fonts:
        - asset: assets/fonts/Poppins-Regular.ttf
        - asset: assets/fonts/Poppins-Italic.ttf
          style: italic
        - asset: assets/fonts/Poppins-Bold.ttf
          weight: 700
        - asset: assets/fonts/Poppins-BoldItalic.ttf
          style: italic
          weight: 700
